name: My first workflow
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: List all files
        run: ls -a
      - name: Basic CPU details
        run: lscpu
      - name: RAM usage (human readable)
        run: free -h
  my-second-job:
    runs-on: ubuntu-latest
    steps:
       - name: Run multiple commands
         run: |
          lscpu
          uname -r
          free -h
          nproc
