name: My first workflow
on: [push, workflow_dispatch]
jobs:
  my-first-job:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World! 1"

  my-second-job:
    if: true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World! 2"
