name: My first workflow
on: [push, workflow_dispatch]
jobs:
  my-first-job:
    env:
      test: "My Test Variable."
      HELLO: "Hello World!"
    runs-on: ubuntu-latest
    steps:
        - run: echo "${{toJson(env.HELLO)}}"
        - run: echo "$HELLO"
